name: ROCm Tests

on:
  push:
    branches: [main]

  pull_request:
  workflow_call:

jobs:
  tests:
    if: github.repository == 'hidet-org/hidet-tilia'
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    runs-on: [self-hosted, Linux, X64, amdgpu]
    container:
      image: rocm/dev-ubuntu-22.04
      options: --device=/dev/kfd --device=/dev/dri --group-add video
    steps:
      - name: Install dependencies via apt
        run: |
          apt update && DEBIAN_FRONTEND=noninteractive apt install -y ccache git graphviz

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.19.x'

      - name: Install dependencies via pip
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio 
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build hidet
        run: |
          bash scripts/wheel/build_wheel.sh
          WHEEL=$(find ./scripts/wheel/built_wheel -maxdepth 1 -name '*.whl')
          echo "WHEEL_NAME=$WHEEL" >> $GITHUB_ENV
          echo "Built wheel: ${{ env.WHEEL_NAME }}"

      - name: Install hidet
        run: |
          pip install --no-deps --force-reinstall ${{ env.WHEEL_NAME }}

      - name: List installed packages
        run: |
          pip list

      - name: Print Hello World
        run: |
          echo "Hello World"

      # Run tests

      - name: Run tests
        run: |
          python -m pytest -v --durations=20 --clear-cache ./tests

